FROM node:17-alpine

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

ENV NODE_OPTIONS --openssl-legacy-provider

RUN apk add git python3
RUN npm i -g pnpm

WORKDIR /app

COPY package.json .
RUN pnpm i

COPY . .
RUN pnpm i

CMD ["pnpm", "start"]
